### ISSUE TITLE
Rule does not apply

### ISSUE THREAD

**Issue by JangXa** [zakk4223/hyprland-workspace-rules#1]
After installing the plugin with hyprpm I added the rule:
 `monitorwsrule=DP-2,gapsIn:6,layoutopt:orientation:top`

No error message occurred. Opening a workspace on DP-2 the behaviour from default hasnt changed.

Ive tried disabling all other plugins, reinstalling.

**Comment by zakk4223** [comment]
What does the output of 'hypctl plugins list' look like?

**Comment by JangXa** [comment]
Hey, this is the output.

```
hyprctl plugin list

Plugin split-monitor-workspaces by Duckonaut:
	Handle: 5573a1302100
	Version: 1.1.0
	Description: Split monitor workspace namespaces

Plugin Monitor WS rules by Zakk:
	Handle: 5573a1334300
	Version: 1.0
	Description: Allow workspace rules per monitor
```

**Comment by JangXa** [comment]
Sorry, while testing I apparently did not unload split-monitor-workspaces. Issue by: 
https://github.com/Duckonaut/split-monitor-workspaces/issues/37
